# 1단계: 빌드 환경
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# 프로젝트 파일 복사 및 복원
COPY *.csproj ./
RUN dotnet restore

# 전체 앱 복사 및 빌드
COPY . ./
RUN dotnet publish -c Release -o /app/publish


# 2단계: 런타임 환경
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

COPY --from=build /app/publish .


# 포트 설정 (필요시 변경)
EXPOSE 5258

ENTRYPOINT ["dotnet", "auth.dll"]